PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ex:  <http://example.org/>

SELECT DISTINCT ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4 (concat("(⊕",group_concat(?fprov),")")AS ?f) WHERE { 
    VALUES ( ?bgp1 ) { ( <http://172.21.233.17:7306/repositories/ratingsite6>) }
    SERVICE ?bgp1 {
        {  {
            # const bsbm:Product98654
      <<  ?review bsbm:reviewFor ?localProductXYZ >> ex:occurrenceOf ?fprov0.
      <<  ?localProductXYZ owl:sameAs bsbm:Product98654 >> ex:occurrenceOf ?fprov1.
      <<  ?review dc:title ?title >> ex:occurrenceOf ?fprov2.
      <<  ?review rev:text ?text >> ex:occurrenceOf ?fprov3.
        # @skip
        FILTER (langMatches( lang(?text), "en" ))
      <<  ?review bsbm:reviewDate ?reviewDate >> ex:occurrenceOf ?fprov4.
      <<  ?review rev:reviewer ?reviewer >> ex:occurrenceOf ?fprov5.
      <<  ?reviewer foaf:name ?reviewerName >> ex:occurrenceOf ?fprov6.
       
         << ?review bsbm:rating1 ?rating1 >> ex:occurrenceOf ?fprov7.
        << ?review bsbm:rating2 ?rating2 >> ex:occurrenceOf ?fprov8. 
       <<  ?review bsbm:rating3 ?rating3 >> ex:occurrenceOf ?fprov9. 
      <<  ?review bsbm:rating4 ?rating4 >> ex:occurrenceOf ?fprov10.   
           BIND(concat("(⊗", STR(?fprov0), STR(?fprov1), STR(?fprov2), STR(?fprov3), STR(?fprov4),STR(?fprov5),STR(?fprov6),STR(?fprov7),STR(?fprov8),STR(?fprov9),STR(?fprov10), ")") AS ?rightunion0)    
        }
        UNION
        
        { 
             SELECT DISTINCT ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4 (CONCAT("(⊖",?rightoptional0,",",GROUP_CONCAT(?leftoptional0) ,",",")")  AS ?leftunion0)  WHERE{   
            {  # const bsbm:Product98654
      <<  ?review bsbm:reviewFor ?localProductXYZ >> ex:occurrenceOf ?fprov11.
      <<  ?localProductXYZ owl:sameAs bsbm:Product98654 >> ex:occurrenceOf ?fprov12.
      <<  ?review dc:title ?title >> ex:occurrenceOf ?fprov13.
      <<  ?review rev:text ?text >> ex:occurrenceOf ?fprov14.
        # @skip
        FILTER (langMatches( lang(?text), "en" ))
      <<  ?review bsbm:reviewDate ?reviewDate >> ex:occurrenceOf ?fprov15.
      <<  ?review rev:reviewer ?reviewer >> ex:occurrenceOf ?fprov16.
      <<  ?reviewer foaf:name ?reviewerName >> ex:occurrenceOf ?fprov17.
  BIND(concat("(⊗", STR(?fprov11), STR(?fprov12), STR(?fprov13), STR(?fprov14), STR(?fprov15),STR(?fprov16),STR(?fprov17), ")") AS ?rightoptional0) 
            }
        OPTIONAL { 
         << ?review bsbm:rating1 ?rating1 >> ex:occurrenceOf ?fprov18.
        << ?review bsbm:rating2 ?rating2 >> ex:occurrenceOf ?fprov19. 
       <<  ?review bsbm:rating3 ?rating3 >> ex:occurrenceOf ?fprov20. 
      <<  ?review bsbm:rating4 ?rating4 >> ex:occurrenceOf ?fprov21.
          BIND(concat("(⊗", STR(?fprov18), STR(?fprov19), STR(?fprov20), STR(?fprov21), ")") AS ?leftoptional0)      
            }
         
    }GROUP BY ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4 ?rightoptional0
    }
            BIND (CONCAT("(⊕",COALESCE(?rightunion0," "),",",COALESCE(?leftunion0," "),",",")")  AS ?funion0) .
}
         BIND(concat("( ⊛",STR(?bgp1),"{",STR(?funion0),"}") AS ?fprov)
    }
}
GROUP BY ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4
ORDER BY ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4
LIMIT 20